services:
  order-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - order-service
    volumes:
      - postgres:/var/lib/postgresql/data

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    environment:
      - ORDER_DB_HOST=order-db
    ports:
      - "8091:8091"
    depends_on:
      - order-db
    networks:
      - order-service

networks:
  order-service:
    ipam:
      driver: default

volumes:
  postgres:
    driver: local