server:
  port: 8091
---
spring.cloud:
  function:
    definition: supplierQueue; consumerQueue
  stream:
    bindings:
      supplierQueue-out-0:
        destination: order-created
      consumerQueue-in-0:
        destination: order-updated
        group: order-service-order-created-consumer-group
    kafka:
      binder:
        brokers: ${KAFKA_HOST:localhost}:9092
        replication-factor: 1
---
spring:
  jpa:
    defer-datasource-initialization: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:5432/orderdb
    user: admin
    password: admin
  r2dbc:
    url: r2dbc:postgresql://${ORDER_DB_HOST:localhost}:5432/orderdb
    username: admin
    password: admin


